### ISSUE TITLE
Native image build fails with JOOQ 3.14

### ISSUE THREAD

**Issue by morki** [micronaut-graal-tests/micronaut-jooq-graal#9]
Hi @ilopmar,

JOOQ 3.14 was released and merged into bom of `2.2.x` Micronaut branch.

But it fails to build native image with following error:

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1795)
Call path from entry point to java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(Method, Class): 
        at java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1793)
        at org.jooq.tools.reflect.Reflect$1.invoke(Reflect.java:802)
        at com.sun.proxy.$Proxy350.toString(Unknown Source)
        at java.lang.String.valueOf(String.java:2951)
        at java.io.PrintStream.print(PrintStream.java:745)
        at java.io.PrintStream.println(PrintStream.java:882)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:766)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
```

I tried to debug it even with suggested ` -H:+ReportExceptionStackTraces` flag, but for me, no additial helpful info was provided.

When compiled with `--report-unsupported-elements-at-runtime` everything is working fine in runtime.

**Steps to reproduce:** 

- add `version('3.14.0')` into `jooq` configuration block inside this repository `build.gradle` to force usage of version 3.14 (I tried with `postgres` branch)

Can you please try to help me with debuging this issue and pointing to the right direction? I am happy to create PR then.

Thank you very much.

**Comment by ilopmar** [comment]
I have no idea why the test application is not using the latest jOQQ version defined in Micronaut BOM because our test app hasn't caught this, and it is passing: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/806551747

I'll try to take a closer look soon, but it seems something have changed on jOQQ side that broke this. Maybe it's worth it to take a look at the release notes or ask directly in their issue tracker.

**Comment by lukaseder** [comment]
> Maybe it's worth it to take a look at the release notes or ask directly in their issue tracker.

I'm here. 👋

**Comment by lukaseder** [comment]
... but it doesn't ring a bell. jOOQ hardly uses this `Reflect.as()` call to proxy stuff, internally...

**Comment by ilopmar** [comment]
Woow @lukaseder that was fast!

I see this error while generating the classes (not sure if it's related):

```
Oct 22, 2020 5:22:59 PM org.jooq.tools.JooqLogger info
INFO: Generating Indexes       
Oct 22, 2020 5:22:59 PM org.jooq.tools.JooqLogger info
INFO: Skipping empty indexes   
Oct 22, 2020 5:22:59 PM org.jooq.tools.JooqLogger info
INFO: Generating table records 
Oct 22, 2020 5:22:59 PM org.jooq.tools.JooqLogger info
INFO: Generating record        : OwnerRecord.java
java.lang.IllegalStateException: A formatting error has been produced by https://github.com/jOOQ/jOOQ/issues/10196
        at org.jooq.codegen.GeneratorWriter.print(GeneratorWriter.java:162)
        at org.jooq.codegen.GeneratorWriter.print(GeneratorWriter.java:143)
        at org.jooq.codegen.GeneratorWriter.println(GeneratorWriter.java:274)
        at org.jooq.codegen.JavaGenerator.printTableJPAAnnotation(JavaGenerator.java:6734)
        at org.jooq.codegen.JavaGenerator.generateRecord0(JavaGenerator.java:1419)
        at org.jooq.codegen.JavaGenerator.generateRecord(JavaGenerator.java:1378)
        at org.jooq.codegen.JavaGenerator.generateRecords(JavaGenerator.java:1364)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:610)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:538)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:437)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:879)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:200)
Oct 22, 2020 5:22:59 PM org.jooq.tools.JooqLogger info
INFO: Generating record        : PetRecord.java
java.lang.IllegalStateException: A formatting error has been produced by https://github.com/jOOQ/jOOQ/issues/10196
        at org.jooq.codegen.GeneratorWriter.print(GeneratorWriter.java:162)
        at org.jooq.codegen.GeneratorWriter.print(GeneratorWriter.java:143)
        at org.jooq.codegen.GeneratorWriter.println(GeneratorWriter.java:274)
        at org.jooq.codegen.JavaGenerator.printTableJPAAnnotation(JavaGenerator.java:6734)
        at org.jooq.codegen.JavaGenerator.generateRecord0(JavaGenerator.java:1419)
        at org.jooq.codegen.JavaGenerator.generateRecord(JavaGenerator.java:1378)
        at org.jooq.codegen.JavaGenerator.generateRecords(JavaGenerator.java:1364)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:610)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:538)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:437)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:879)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:200)
Oct 22, 2020 5:22:59 PM org.jooq.tools.JooqLogger info
INFO: Forcing type             : public.pet.type to <userType>example.jooq.domain.Pet.PetType</userType><converter>example.jooq.converters.PetTypeConverter</converter><includeExpression>PET\.TYPE</includeExpression><nullability>ALL</nullability><objectType>ALL</objectType>
Oct 22, 2020 5:22:59 PM org.jooq.tools.JooqLogger info
INFO: Generating record        : PgpArmorHeadersRecord.java
java.lang.IllegalStateException: A formatting error has been produced by https://github.com/jOOQ/jOOQ/issues/10196
        at org.jooq.codegen.GeneratorWriter.print(GeneratorWriter.java:162)
        at org.jooq.codegen.GeneratorWriter.print(GeneratorWriter.java:143)
        at org.jooq.codegen.GeneratorWriter.println(GeneratorWriter.java:274)
        at org.jooq.codegen.JavaGenerator.printTableJPAAnnotation(JavaGenerator.java:6734)
        at org.jooq.codegen.JavaGenerator.generateRecord0(JavaGenerator.java:1419)
        at org.jooq.codegen.JavaGenerator.generateRecord(JavaGenerator.java:1378)
        at org.jooq.codegen.JavaGenerator.generateRecords(JavaGenerator.java:1364)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:610)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:538)
        at org.jooq.codegen.JavaGenerator.generate(JavaGenerator.java:437)
        at org.jooq.codegen.GenerationTool.run0(GenerationTool.java:879)
        at org.jooq.codegen.GenerationTool.run(GenerationTool.java:233)
        at org.jooq.codegen.GenerationTool.generate(GenerationTool.java:228)
        at org.jooq.codegen.GenerationTool.main(GenerationTool.java:200)
Oct 22, 2020 5:22:59 PM org.jooq.tools.JooqLogger info
INFO: Table records generated  : Total: 923.673ms, +40.398ms
```

And then I get another different error when creating the native-image, which seems is related to charsets (??): 

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
	at parsing java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1233)
Call path from entry point to java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(Method, Class): 
	at java.lang.invoke.MethodHandles$Lookup.unreflectSpecial(MethodHandles.java:1231)
	at org.jooq.tools.reflect.Reflect$1.invoke(Reflect.java:802)
	at com.sun.proxy.$Proxy347.hashCode(Unknown Source)
	at java.util.HashMap.hash(HashMap.java:339)
	at java.util.HashMap.get(HashMap.java:557)
	at com.oracle.svm.core.jdk.Target_java_nio_charset_Charset.lookup(CharsetSubstitutions.java:74)
	at java.nio.charset.Charset.isSupported(Charset.java:505)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VARARGS:Ljava_nio_charset_Charset_2_0002eisSupported_00028Ljava_lang_String_2_00029Z(generated:0)
```

**Comment by morki** [comment]
Maybe it has something to do with new JSON support in 3.14?

There was added some reflection to `Convert` class to support Jackson and GSON if they are on the classpath.
- https://github.com/jOOQ/jOOQ/blob/d1644a9fc1caafb5a4588b50b49810afef8e984c/jOOQ/src/main/java/org/jooq/tools/Convert.java#L194
- https://github.com/jOOQ/jOOQ/blob/d1644a9fc1caafb5a4588b50b49810afef8e984c/jOOQ/src/main/java/org/jooq/tools/Convert.java#L1076

@ilopmar do you think it can be the problem?

**Comment by lukaseder** [comment]
> Woow @lukaseder that was fast!

I was pinged.

> I see this error while generating the classes (not sure if it's related):

I think those things are already addressed, and not related: https://github.com/jOOQ/jOOQ/issues/10782

**Comment by lukaseder** [comment]
> There was added some reflection to `Convert` class to support Jackson and GSON if they are on the classpath.

If that's the case, is there anything we can do on our side to prevent such things from being released, or to notify you in advance?

**Comment by morki** [comment]
@lukaseder if it will be the problem, do you think you can extract those calls to some SPI like `JsonConverterProvider` with default implementation `DefaultJsonConverterProvider` using this reflection to enable as to substitute this on image build time like we do with `ProxyMapper`?

https://github.com/micronaut-projects/micronaut-sql/blob/master/jooq/src/main/java/io/micronaut/configuration/jooq/graal/ProxyMapperSubstitute.java

**Comment by ilopmar** [comment]
> If that's the case, is there anything we can do on our side to prevent such things from being released, or to notify you in advance?

Not really sure if those changes for GSON/Jackson are related or not. Micronaut is already using Jackson, but it's basically impossible to tell if that is related with the current information on the stacktraces :-(

**Comment by graemerocher** [comment]
The issue could be the fact that jackson is being loaded into the static initializer. It may be necessary to compute what is happening here at build time https://github.com/jOOQ/jOOQ/blob/d1644a9fc1caafb5a4588b50b49810afef8e984c/jOOQ/src/main/java/org/jooq/tools/Convert.java#L194

Or at least delay this class to runtime initialization and register the necessary reflections

**Comment by lukaseder** [comment]
I'll look into it tomorrow, @morki. There should be an SPI already, I wonder why there's still some static initialisation as well. It's a really powerful feature, so I wouldn't want to turn it off entirely, but it can probably be abstracted more.

The static initialisation can definitely be delayed. It doesn't have to happen eagerly.

**Comment by morki** [comment]
@graemerocher I tried to add `--initialize-at-run-time=org.jooq.tools.Convert` but no difference in reported error.

I will try to build jOOQ locally and make some changes to find out where this error is coming from.

**Comment by morki** [comment]
It probably will not be related to reflection in `Convert` class, I built jOOQ locally with those parts deleted and use this version for building this testing application, but the error is still the same... :(

**Comment by graemerocher** [comment]
At least you have a workaround with `--report-unsupported-elements-at-runtime` until we investigate

**Comment by ilopmar** [comment]
I've spend some time on this trying different approaches and it doesn't work. Maybe this is not related to jOOQ and after the upgrade we've hit an issue on GraalVM.  
When I see failures like this I always report an issue to the GraalVM team, specially if the "fix" is using `--report-unsupported-elements-at-runtime`: https://github.com/oracle/graal/issues/2940

**Comment by ilopmar** [comment]
BTW @morki we haven't detect this on our CI because the Gradle plugin was forcing an old jOOQ version even if Micronaut BOM includes the new one.
I'm not sure if we can get the version directly from Micronaut BOM, but in the mean time you can do to force the same version:

```groovy
jooq {
    ...
    version = '3.14.0'
    ...
}
```

**Comment by morki** [comment]
@ilopmar thank you very much for your time on this. Maybe in meantime we can create another branch with an explicit version `3.14.0` to make Gitlab CI test this for us and if it will be error in GraalVM, we can see if it was fixed in nighty builds. 

What do you think? I can create a PR for this.

**Comment by graemerocher** [comment]
I have discussed this with the GraalVM team, the issue may be resolved in 20.3 / master, @ilopmar could you try that?

**Comment by ilopmar** [comment]
@graemerocher I've tried it and it doesn't work. Same error as reported before https://github.com/oracle/graal/issues/2940

**Comment by ilopmar** [comment]
> @ilopmar thank you very much for your time on this. Maybe in meantime we can create another branch with an explicit version `3.14.0` to make Gitlab CI test this for us and if it will be error in GraalVM, we can see if it was fixed in nighty builds.
> 
> What do you think? I can create a PR for this.

The current `2.2.x_...` branches should test jOOQ 3.14.0. I'll force the version in those branches and push the changes.

**Comment by ilopmar** [comment]
@morki The test application fails now https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/809061532 so if it starts passing again we should know.

**Comment by morki** [comment]
This is now posible with MethodHandle support in GraalVM 21.0, so I am closing.
